T34555: Adding sites from gnome-pwa-lists
endlessm/gnome-software-data pull request #37
Opened 2023-03-08 06:44 UTC by MichaelDrydenEndless

Added sites from the gnome-pwa-lists to [eos-extra-pwa.yaml](https://github.com/endlessm/gnome-software-data/blob/master/app-info/eos-extra-pwa.yaml) and made the from_head functions a bit more robust and versatile

https://phabricator.endlessm.com/T34555

2023-03-08 09:24 UTC, wjt commented on app-info/metainfo/org.gnome.Software.WebApp_e41134be0ce95da0832878faa90cf3473b1b52d7.metainfo.xml
> +  <summary>Squoosh</summary>
Not a great summary :)

2023-03-08 09:29 UTC, wjt commented on app-info/metainfo/org.gnome.Software.WebApp_e636aa5f2069f6e9c02deccc7b65f43da7985e32.metainfo.xml
> +  <description>An alternative web client for Mastodon, focused on speed and simplicity.</description>
Summary and description should not be the same string

2023-03-08 09:29 UTC, wjt commented on app-info/metainfo/org.gnome.Software.WebApp_e730d810bf154c7818b460479ea7826140099a7a.metainfo.xml
> +  <summary>Instagram</summary>
Summary should not be the same as the name

2023-03-08 09:30 UTC, wjt commented on app-info/metainfo/org.gnome.Software.WebApp_e730d810bf154c7818b460479ea7826140099a7a.metainfo.xml
> +  <description>Create an account or log in to Instagram - A simple, fun &amp; creative way to capture, edit &amp; share photos, videos &amp; messages with friends &amp; family.</description>
"create an account or log into Instagram" should be removed. The rest of the description looks fine, could also be the summary

2023-03-08 09:30 UTC, wjt commented on app-info/metainfo/org.gnome.Software.WebApp_ea52ad18346faac27072cd1654243dfb7c70ef14.metainfo.xml
> +  <summary>Excalidraw — Collaborative whiteboarding made easy</summary>
```suggestion
  <summary>Collaborative whiteboarding made easy</summary>
```

2023-03-09 18:07 UTC, dbnicholson requested changes
Looking good, but I think a little more polish is needed.

2023-03-09 18:07 UTC, dbnicholson commented on app-info/pwa-metainfo-generator.py
> +    else:
This whole block looks exactly like what `prop_from_head` is doing and it appears `prop_from_head` isn't used anywhere. I think this whole part could be written like:

```
keywords_value = prop_from_head("keywords")
if keywords_value:
    keywords = keywords_value.split(", ")
else:
    keywords = []
```

2023-03-09 18:07 UTC, dbnicholson commented on app-info/eos-extra-pwa.yaml
> +  description:
I think you need to come up with some description here. You also need to run `pwa-metainfo-generator.py` again and commit the changes to the metainfo files.

2023-03-14 15:37 UTC, wjt requested changes
Some of the categories are not quite right. I left notes on a couple but that's not exhaustive, e.g. Instagram has the same problem with comma-separated names in a single `<category>` tag rather than one `<category>` tag per category. This is probably due to not formatting the input YAML quite right.

2023-03-14 17:02 UTC, dbnicholson approved these changes
I'm going to merge this as is since we have too many outstanding branches. I think once we get all the desired apps in, we can take another sweep through the appstream to really polish it.

2023-03-14 17:02 UTC, merged