eos-extra-pwa: Include Epithany Compatible Web Apps
endlessm/gnome-software-data pull request #39
Opened 2023-03-11 06:43 UTC by MichaelDrydenEndless

Added sites from Epithany Compatible Web Apps Spreadsheet

https://phabricator.endlessm.com/T34583

2023-03-11 06:44 UTC, MichaelDrydenEndless commented
I tried running this through the pwa-metainfo-generator but got a No Manifest error that prevented me from generating the XML files.

2023-03-13 17:54 UTC, dbnicholson requested changes
Please generate and commit the appstream XML so we can see what the final output looks like.

2023-03-13 17:54 UTC, dbnicholson commented
> I tried running this through the pwa-metainfo-generator but got a "No Manifest error" starting with the sites added here that prevented me from generating the XML files.

Which site was causing that?

2023-03-14 17:24 UTC, dbnicholson commented
> Here is the list of which ones do/don't have manifests: No Manifest:

OK, I think we'll have to change the generator to not require a manifest. When this was initially conceived, the generator was a simple manifest to appstream converter. Now we're also trying to gather the data from other places and the manifest is just one source.

Here's what I'd like you to do. Remove `ManifestNotFoundException`. Where it was used, instead return an empty dictionary like `return {}`. Wherever the code was looking up an entry in the manifest like `manifest['something']`, change it to `manifest.get('something')`. This will return `None` if there's no `something` entry in the manifest dictionary (which will be the case if there's no manifest at all). If `None` isn't appropriate, you can use a different default fallback the 2nd parameter to `get`. Like, `manifest.get('icons', [])` might be appropriate since the code all treats the icons as a list.

> Additionally, I found that there were a number of sites that threw an error that prevented me from retrieving the manifest 403 Client Error: Forbidden for url:
> 
> * https://www.canva.com/
> * https://www.imdb.com/
> * https://accuweather.com/
> * https://quizlet.com/
> * https://cookpad.com/us

Ugh. These are all sites that appear to either block specific user agents in the request or require JavaScript to pass a captcha. We might be able to put something in the generator to deal with that, but I don't think it's really worth the effort.

As an FYI, in #38 I'm removing the YAML setup and the generator will just provide a getting started template and then you're expected to directly edit the appstream until it's appropriate. In that case, we just won't run the generator for these sites at all and the appstream will be built from scratch.

For the moment, just skip these and we'll come back to them.

2023-03-15 06:01 UTC, MichaelDrydenEndless commented
Some of the committed files had conflicts but I think I cleared all those up and got it all current.

2023-03-15 19:36 UTC, dbnicholson commented
This is looking pretty good, but now there are a bunch of conflicts since #38 and #40 were merged. An important thing to note is that #38 got rid of the YAML file. Instead, you'll generate the metainfo XML files and then edit them directly.

In GitHub Desktop, you can go to Branch -> Rebase current branch and then choose master. This will hit conflicts that you have to resolve. The rebase dialog will prompt you to address them, but it can be tricky to understand what's going on. In the case of the YAML file, you would say that you want to keep the deleted version from master. For the metainfo files, you have to open them in an editor and fix up the issues. https://youtu.be/OXtdxHTh2oY is a good description of what's happening. When all the issues are resolved, GitHub Desktop will tell you you can continue.

Since this one was pretty difficult, I did the rebase myself and pushed it to [T34583-dbn](https://github.com/endlessm/gnome-software-data/tree/T34583-dbn). I did 2 other things that might be interesting there:

* I [reordered](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/managing-commits/reordering-commits) the script fix so it came first in the series.
* I split the metainfo changes into 2 commits - the first just fixes the existing GNOME PWA ones, and the second adds the new web apps. I did Undo commit in GitHub Desktop and then unchecked the new files (actually I did it on the CLI by not adding the new files for the first commit, but I think it's the same idea).

If you want to just use my branch, you can do `git reset --hard origin/T34583-dbn` and `git push --force origin T34583`.

2023-03-15 19:44 UTC, dbnicholson requested changes
Here's a few comments on the metainfo files. Since the YAML file has been removed, please add the URL for each new app to `app-info/eos-extra-pwa.txt` so we have an easy record for each PWA we're managing.

2023-03-15 19:44 UTC, dbnicholson commented on app-info/metainfo/org.gnome.Software.WebApp_092f50a2d722b80d5fad80fefb89559d0c56b3e2.metainfo.xml
> +  <name />
This needs a name.

2023-03-15 19:44 UTC, dbnicholson commented on app-info/metainfo/org.gnome.Software.WebApp_092f50a2d722b80d5fad80fefb89559d0c56b3e2.metainfo.xml
> +  <project_license>GPL-2.0-or-later</project_license>
All the `<description>` tags need to have markup. Sorry I didn't catch this earlier. You can just take each one and add a `<p>` at the beginning and `</p>` at the end to wrap it in a paragraph.

2023-03-15 19:44 UTC, dbnicholson commented on app-info/metainfo/org.gnome.Software.WebApp_3a023ac6fc65c87ba5c88c1a1bb07edef7c6b8c4.metainfo.xml
> +  <name />
Missing name.

2023-03-15 19:44 UTC, dbnicholson commented on app-info/metainfo/org.gnome.Software.WebApp_506b15e469a34ac26f7b3235568af3c0cc5b3164.metainfo.xml
> +  <name />
Missing name.

2023-03-15 19:44 UTC, dbnicholson commented on app-info/metainfo/org.gnome.Software.WebApp_52b732dd06d99298b6e9bfccc17e25e0ac8b2bcb.metainfo.xml
> +  <name />
Missing name.

2023-03-15 19:44 UTC, dbnicholson commented on app-info/metainfo/org.gnome.Software.WebApp_7236bcfcc34bbdb54ff31a49ec40cdc2fd50c6e0.metainfo.xml
> +  <name />
Missing name.

2023-03-15 19:44 UTC, dbnicholson commented on app-info/metainfo/org.gnome.Software.WebApp_9e300f8f00666f4790eb7ed1b9e1c92c598759cb.metainfo.xml
> +  <name />
Missing name.

2023-03-16 06:50 UTC, MichaelDrydenEndless commented
I've added the URLs and fixed the metainfo xml files.

2023-03-16 22:06 UTC, dbnicholson approved these changes
I think this is good enough for now. All the apps need screenshots and the appstream catalog (the `eos-extra.xml` file) needs to be regenerated to actually use this data.

2023-03-16 22:06 UTC, merged